-- Populate sample data for the oblong table product
UPDATE products SET 
  long_description = E'## Professional-Grade Oblong Banquet Table\n\nEngineered for the demanding hospitality environment, the LL Oblong Table delivers exceptional durability with a clean, professional aesthetic. At 6 feet × 2.5 feet (1830L × 760W × 760H mm), it''s the perfect size for banquet halls, conference rooms, and large-scale catering events.\n\n## Construction & Materials\n\nThe tabletop features **18mm marine-grade plywood** with a **3mm high-density foam layer** and **white PVC padded surface** — providing a smooth, stain-resistant work surface that cleans effortlessly between events. The **T-mold black rubber edge** protects against chipping and provides a finished, professional look.\n\nThe base is constructed from **30×30×1.2mm iron frame** with a **black powder-coated finish** that resists scratches, rust, and the wear of daily commercial use.\n\n## Why HoReCa Professionals Choose This Table\n\nTrusted by over 300 hotels, restaurants, and event companies across Myanmar, this table delivers:\n\n- **Commercial Durability**: Rated for 200kg+ distributed load capacity\n- **Foldable Design**: Legs fold flat for efficient storage and transport\n- **Stackable**: Save up to 60% floor space when stored\n- **Easy Maintenance**: Wipe-clean PVC surface resists stains and moisture\n- **Professional Finish**: Consistent white surface ideal for tablecloth or bare use\n\n## Ideal Applications\n\nBanquet halls, hotel conference rooms, wedding venues, outdoor catering events, exhibition spaces, training centers, and any establishment requiring reliable, large-format table solutions.\n\n## Warranty & Support\n\nBacked by a 2-year structural warranty. Replacement parts available. Contact your IKON account manager for bulk pricing and custom configurations.',
  specifications = '{"Material (Top)": "18mm Marine-Grade Plywood", "Surface": "3mm Foam + White PVC Padded", "Edge": "T-Mold Black Rubber", "Frame Material": "30×30×1.2mm Iron", "Frame Finish": "Black Powder Coated", "Length": "1830mm (6 ft)", "Width": "760mm (2.5 ft)", "Height": "760mm", "Weight": "18 kg", "Load Capacity": "200 kg (distributed)", "Foldable": "Yes — Legs fold flat", "Stackable": "Yes", "Indoor/Outdoor": "Indoor (covered outdoor OK)", "Color (Top)": "White", "Color (Frame)": "Black", "Country of Origin": "Myanmar", "Warranty": "2-Year Structural"}'::jsonb
WHERE id = 'f1d68276-1512-46e5-aee2-f38a034af49c';

-- Insert pricing tiers
INSERT INTO pricing_tiers (product_id, min_qty, max_qty, unit_price) VALUES
  ('f1d68276-1512-46e5-aee2-f38a034af49c', 1, 5, 125000),
  ('f1d68276-1512-46e5-aee2-f38a034af49c', 6, 24, 110000),
  ('f1d68276-1512-46e5-aee2-f38a034af49c', 25, 99, 97500),
  ('f1d68276-1512-46e5-aee2-f38a034af49c', 100, NULL, 85000)
ON CONFLICT DO NOTHING;