// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqabwolwhrtrygmhaipg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxYWJ3b2x3aHJ0cnlnbWhhaXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NzkzMDYsImV4cCI6MjA4ODQ1NTMwNn0.KAZ2oG4wdvnP9p9J8z1C62lRa5a_dZPHXBj5KhwMlag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});